name: json_to_agha
description: "A new Flutter project."

#publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc:
  clipboard:
  sizer:
  auto_size_text:
  json_to_dart:
    git: 
      url : https://github.com/javiercbk/json_to_dart.git
  bitsdojo_window:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: JameelFaimly  #fontFamily: in TextStyle
      fonts:
        - asset: assets/fonts/jameel_agha.ttf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
